package pkg.virdin.wayland

/**
 * Compile-time configuration.
 *
 * This file is generated by build.gradle.kts based on the Gradle property:
 *   virdin.wayland.useBundledBinary  (default: true)
 *
 * DO NOT EDIT MANUALLY — re-run Gradle to regenerate.
 */
object BuildConfig {
    /**
     * When true, [BinaryManager] extracts the [wayland-helper] binary that
     * was bundled inside the JAR at build time.
     *
     * When false, [BinaryManager] searches the system PATH (or the path set
     * via [BinaryManager.systemBinaryPath]).
     */
    const val USE_BUNDLED_BINARY: Boolean = true   // replaced by Gradle

    const val BINARY_VERSION: String = "1.0.0"    // replaced by Gradle
}
